baseURL = 'https://thecategorytheorist.github.io/categorytheory/'
languageCode = 'en-us'
title = 'The Category Theorist'
paginate = 3
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "archie"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true



[Params]
  mode="auto"

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Stories"
url = "/stories"
weight = 3