baseURL = 'https://thecategorytheorist.github.io/categorytheory/'
languageCode = 'en-us'
title = 'The Category Theorist'
paginate = 3
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "archie"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true



[Params]
  mode="auto"

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2


[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4